services:
  app:
    build:
      context: .
    ports:
      - "8501:8501"
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SQL_SERVER=db
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - sqlserver_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver_data: